sylius_resource:
    resources:
        aality_reassurance.reassurance:
            classes:
                model: Aality\ReassuranceBundle\Entity\Reassurance\Reassurance
                form: Aality\ReassuranceBundle\Form\Type\ReassuranceType
                

    
services:
    Aality\ReassuranceBundle\EventSubscriber\AdminMenuSubscriber:
        tags:
            - { name: kernel.event_subscriber }
        arguments:
          [ '@security.helper' ]
    Aality\ReassuranceBundle\Form\Type\ReassuranceType:
        arguments:
            $projectDir: '%kernel.project_dir%'
        tags: [ 'form.type' ]
        

    Aality\ReassuranceBundle\Controller\ReassuranceController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]
        
    Aality\ReassuranceBundle\Controller\ConfigurationController:
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]


sylius_grid:
    grids:
        aality_reassurance:
            fields:
                title:
                    type: string
                image:
                    type: twig
                    label: Image
                    path: .
                    options:
                        template: '@ReassuranceBundle/admin/reassurance/Grid/Field/image.html.twig'
    
            driver:
                name: doctrine/orm
                options:
                    class: Aality\ReassuranceBundle\Entity\Reassurance\Reassurance
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/vendor/aality/sylius-reassurance-bundle/templates': ReassuranceBundle

parameters:
    reassurance_images_directory: '%kernel.project_dir%/public/uploads/reassurances'


sylius_twig_hooks:
    hooks:
        'sylius_admin.reassurance.index':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0
        
        'sylius_admin.reassurance.index.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 300
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 200
            custom_content:
                template: '@ReassuranceBundle/admin/reassurance-dashboard-content.html.twig'
