aality_reassurance:
  resource: |
    alias: aality_reassurance.reassurance
    section: admin
    templates: "@SyliusReassuranceBundle/admin/reassurance"
    grid: aality_reassurance
    redirect: index
  type: sylius.resource
  prefix: admin

aality_reassurance_admin_configuration:
  path: /admin/reassurance/configuration
  controller: Aality\SyliusReassuranceBundle\Controller\ConfigurationController::configure
  methods: [ GET, POST ]
